/**
 * Sidebar configuration
 * Auto-generated from docs.config.ts
 */
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {docs} from './docs.config';

const sidebars: SidebarsConfig = Object.fromEntries(
  docs.map(doc => [doc.id, [{type: 'autogenerated', dirName: '.'}]])
);

export default sidebars;
